[package]
name = "router2"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
async-trait = "0.1"
bytes = "1.1"
data_types = { path = "../data_types" }
dml = { path = "../dml" }
flate2 = "1.0"
futures = "0.3.21"
generated_types = { path = "../generated_types" }
hashbrown = "0.12"
hyper = "0.14"
influxdb_line_protocol = { version = "0.1.0", path = "../influxdb_line_protocol" }
iox_catalog = { path = "../iox_catalog" }
metric = { path = "../metric" }
mutable_batch = { path = "../mutable_batch" }
mutable_batch_lp = { path = "../mutable_batch_lp" }
observability_deps = { path = "../observability_deps" }
parking_lot = "0.12"
predicate = { path = "../predicate" }
serde = "1.0"
serde_urlencoded = "0.7"
siphasher = "0.3"
thiserror = "1.0"
time = { path = "../time" }
tokio = { version = "1", features = ["rt-multi-thread", "macros"] }
tonic = "0.6"
trace = { path = "../trace/" }
workspace-hack = { path = "../workspace-hack"}
write_buffer = { path = "../write_buffer" }

[dev-dependencies]
assert_matches = "1.5"
criterion = { version = "0.3.4", features = ["async_tokio", "html_reports"] }
lazy_static = "1.4.0"
paste = "1.0.6"
pretty_assertions = "1.1.0"
rand = "0.8.3"
schema = { path = "../schema" }

[[bench]]
name = "sharder"
harness = false

[[bench]]
name = "e2e"
harness = false
