[package]
name = "tracker"
version = "0.1.0"
authors = ["Raphael Taylor-Davies <r.taylordavies@googlemail.com>"]
edition = "2021"
description = "Utilities for tracking resource utilisation within IOx"

[dependencies]

futures = "0.3"
hashbrown = "0.12"
lock_api = "0.4.4"
metric = { path = "../metric" }
observability_deps = { path = "../observability_deps" }
parking_lot = "0.12"
pin-project = "1.0"
time = { path = "../time" }
tokio = { version = "1.13", features = ["macros", "parking_lot", "sync", "time"] }
tokio-util = { version = "0.7.0" }
workspace-hack = { path = "../workspace-hack"}

[dev-dependencies]
# Need the multi-threaded executor for testing
tokio = { version = "1.13", features = ["macros", "parking_lot", "rt-multi-thread", "time"] }
